version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Create Scratch Org
          command: . build/create-scratch-org.sh
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Develop
          command: . build/setup-uat.sh
      #- run: echo "this is the test job"    
  deploy-Dev:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Develop
          command: . build/setup-prod.sh
      - run:
          name: Deploy to Develop
          command: . build/deploy-prod.sh
workflows:
  version: 2.1
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy-Dev:
          requires:
           - build
           - test
           - hold
          filters:
            branches:
              only:
                - Develop

